### ISSUE TITLE
Meta-Analysis Figure

### ISSUE THREAD

**Issue by amyerspigg** [river-corridors-sfa/rc_sfa-rc-3-wenas-modeling#15]
we can make the meta-analysis figure and see what outliers there are. Then dig deeper into those papers to see what explanations they give and that can give insight into what to highlight from modeling

**Comment by JakeCavaiani99** [comment]
@amyerspigg @peterregier  @mbarnes7 

Attached below are some options for the meta-analysis figure. 

Option 1) Broken up by climate
Option 2) Broken up by climate WITH an added layer of time since fire (TSF)
Option 3) Broken up by TSF only. 

Leave comments on anything that you think could improve this figure and of course message me if you need anything 


[site.difference.geom_pointrange.climate.pdf](https://github.com/river-corridors-sfa/rc_sfa-rc-3-wenas-modeling/files/11805009/site.difference.geom_pointrange.climate.pdf)

[site.difference.geom_pointrange.climate.TSF.pdf](https://github.com/river-corridors-sfa/rc_sfa-rc-3-wenas-modeling/files/11805010/site.difference.geom_pointrange.climate.TSF.pdf)

[site.difference.geom_pointrange.TSF.pdf](https://github.com/river-corridors-sfa/rc_sfa-rc-3-wenas-modeling/files/11805011/site.difference.geom_pointrange.TSF.pdf)

**Comment by JakeCavaiani99** [comment]
done
