### ISSUE TITLE
Run Simulations for % area burn x fire severity

### ISSUE THREAD

**Issue by amyerspigg** [river-corridors-sfa/rc_sfa-rc-3-wenas-modeling#2]
- [x] Re-run the simulations with the DOC updated model

**Comment by katiewampler** [comment]
@amyerspigg how do these burned areas look? 
![Wenas_burn_percentage](https://user-images.githubusercontent.com/114772563/231344240-ab0b142b-ded5-4260-9449-ca0777f5cf51.png)

**Comment by amyerspigg** [comment]
I think these look pretty good! @tscheibe, do you agree?

**Comment by katiewampler** [comment]
Okay, I did go ahead and run the scenarios. I tried a few other methods of determing the area burned and they looked worse in my opinion. Data with the area burned and severity are uploaded to the google drive (in the model folder). I just had a quick look and they look reasonable, but if you notice anything weird let me know and I can look into it.

**Comment by amyerspigg** [comment]
Sounds good to me! Thanks

**Comment by amyerspigg** [comment]
Hi Katie, I just ran peter's code with the new scenarios and the data look less reasonable than the old model runs...look at the y axes here? I need to run the code less quickly to make sure its not a bug on my end, but could you check the means for the scenario numbers on your end? Thanks! 

[Old](https://raw.githubusercontent.com/river-corridors-sfa/rc_sfa-rc-3-wenas-modeling/pregier/pr_work/figures/230330_fire_characteristics_bar_charts.png)

[New](https://raw.githubusercontent.com/river-corridors-sfa/rc_sfa-rc-3-wenas-modeling/pregier/pr_work/figures/230414_fire_characteristics_bar_charts.png)

**Comment by katiewampler** [comment]
Hey Allison, I checked the data on my end, and the values from my files are not matching with the y axis for DOC from the new plots. For example for the 90% moderate scenario, just doing a quick pivot table by year, the mean DOC is 1-1.5 mg/L for the burned scenario and 0.3-0.4 mg/L for the unburned. It may be worth checking the units in the plotting script and also the columns that are being pulled. It looks like the sediment and nitrate are plotting the load (kg/day) not concentration not sure if that was purposeful but worth keeping in mind while checking for resonableness.

**Comment by amyerspigg** [comment]
Yep, we were pulling from the load columns!

**Comment by amyerspigg** [comment]
Do you mind giving us a key of the units for all columns

**Comment by katiewampler** [comment]
[Stats Summaries Key.xlsx](https://github.com/river-corridors-sfa/rc_sfa-rc-3-wenas-modeling/files/11291688/Stats.Summaries.Key.xlsx)

Key for the columns attached

**Comment by katiewampler** [comment]
I also checked on the unburned DOC scenario, the mean value does look correct, however it's worth noting that in this case we might want to consider using median instead of mean. It looks like there's maybe a single high DOC value in the burned scenario that's driving up the mean. The medians are much more similar. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/wampleka/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/wampleka/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | Unburned | 10% Low | 90% High
-- | -- | -- | --
mean | 0.468438 | 0.690739 | 1.426461
median | 0.137071 | 0.140478 | 0.234448
max | 5.479287 | 20.48823 | 17.32341
95% Quantile | 2.362037 | 3.039898 | 6.994127
75% Quantile | 0.516169 | 0.592053 | 1.419593



</body>

</html>

**Comment by amyerspigg** [comment]
New scenarios here: https://drive.google.com/drive/folders/1tl1Kf0PxVHbS7wPL4W071pvS1Af3Ji1i
